### ISSUE TITLE
Error while connecting to elastic search cluster on AWS

### ISSUE THREAD

**Issue by ronakvora** [elastic/elasticsearch-js-legacy#6]
Reposting from SO incase anyone here can help:

https://stackoverflow.com/questions/56468702/error-while-connecting-to-elastic-search-cluster-on-aws

RESPOSTED BELOW:

I'm trying to connect to an Elasticsearch cluster using the following code: 

```
const AWS = require('aws-sdk');
const connectionClass = require('http-aws-es');
const elasticsearch = require('elasticsearch');
const credentials = new AWS.EnvironmentCredentials('AWS');

var elasticClient = new elasticsearch.Client({  
      host: 'https://<mycluster>.us-east-1.es.amazonaws.com/',
      log: 'warning',
      port: 443,
      protocol: 'https',
      apiVersion: '6.7',
      connectionClass: connectionClass,
      amazonES: {
        region: 'us-west-2',
        credentials: new AWS.EnvironmentCredentials('AWS')
      }
  });


elasticClient.ping({
  // ping usually has a 3000ms timeout
  requestTimeout: 1000
}, function (error) {
  if (error) {
    console.trace('elasticsearch cluster is down!');
  } else {
    console.log('All is well');
  }
```

But I'm getting the following error in the line `elasticClient.ping`: 

```
Elasticsearch ERROR: 2019-06-05T22:07:38Z
  Error: Request error, retrying
  HEAD https://<mycluster>.us-east-1.es.amazonaws.com/ => The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
      at Log.error (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/elasticsearch/src/lib/transport.js:266:18)
      at done (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/http-aws-es/connector.js:48:7)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Elasticsearch WARNING: 2019-06-05T22:07:38Z
  Unable to revive connection: https://<mycluster>.us-east-1.es.amazonaws.com/

Elasticsearch WARNING: 2019-06-05T22:07:38Z
  No living connections

Trace: elasticsearch cluster is down!
    at /Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/models/tmp.js:331:13
    at respond (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/elasticsearch/src/lib/transport.js:334:9)
    at sendReqWithConnection (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/elasticsearch/src/lib/transport.js:233:7)
    at next (/Users/ronakvora/Documents/Vora/voracommerce/voracommerce_api/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I've tried everything in these posts: 

https://stackoverflow.com/questions/50973930/how-to-make-calls-to-elasticsearch-apis-through-nodejs

https://stackoverflow.com/questions/41148517/elasticsearch-npm-passing-aws-credentials

https://stackoverflow.com/questions/40967394/creating-a-valid-signed-request-to-an-aws-es-instance-from-node-js

https://stackoverflow.com/questions/33204997/aws-elasticsearch-service-iam-role-based-access-policy

but none solve my issue.

**Comment by justinlazaro-iselect** [comment]
having an issue like this too

**Comment by shubhamrc49** [comment]
me too

**Comment by raideltorres** [comment]
If any one face this issue, my solution was to just set the default region

1. `const AWS = require('aws-sdk');`
2. `AWS.config.update({ region: 'us-east-1' });`

As easy as that, but the error message is not helping.

**Comment by elyobo** [comment]
Daft, but same issue here :shrug: Thanks.
